
GET http://localhost:8000/


###
GET http://localhost:8000/users
Authorization: Bearer <access_token>

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "secure"
}


###
GET http://localhost:8000/users/5f890ba1ba6a7d159c4464ba
Authorization: Bearer <access_token>
Content-Type: application/json


###
POST http://localhost:8000/users
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "user@example.com",
    "token": "Hd6hgsj7d%d7%4dbhs&5d",
    "age": 24,
    "image": "IMAGE",
    "description": "Description text"
}

###
DELETE http://localhost:8000/users/5f89085ef090e513b8b0c263

###
PATCH http://localhost:8000/users/5f890ba1ba6a7d159c4464ba
Content-Type: application/json


{
    "first_name": "Johnaattta",
    "last_name": "Doeeaaasa"    
}